name: publish-image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    strategy:
      matrix:
        architecture:
          - arm64
          - amd64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u hwoodiwiss --password-stdin

      - name: Publish Image
        run: |
          dotnet publish --os linux --arch ${{ matrix.architecture }} /t:PublishContainer
