name: publish-image

on:
  workflow_dispatch:
    inputs:
      tag-version:
        description: "The tag version to use for the image"
        required: true
      generate-binlog:
        description: "Should we generate binlogs for the builds"
        type: boolean
        required: false
  push:
    tags:
      - "v*"
  issue_comment:
    types: ["created"]

permissions:
  contents: read
  packages: write

jobs:
  build-images:
    uses: hwoodiwiss/shared-workflows/.github/workflows/publish-containers.yml@add-shared-workflows
    with:
      project: "HwoodiwissHelper"
      ghcr-username: "hwoodiwiss"
